Josh'a auto adventures
FRC2713/Robot2023 pull request #60
Opened 2023-03-11 17:04 UTC by JoshuaGoldberg

potential autos just dropped, also some fixes to other autos

2023-03-11 18:45 UTC, Sid220 approved these changes

2023-03-13 22:06 UTC, tervay commented on src/main/java/frc/robot/commands/OnBridgeUntilMovement.java
> +    backSpeed = 0.4 * (gridside ? -1 : 1) * (DriverStation.getAlliance() == Alliance.Red ? -1 : 1);
Can  we simplify this to something like
```
if (condition1 || condition 2) { robotSpeed = ...; } else { robotSpeed = -...; }
```
and the same thing for back speed?

Will be a bit easier to debug.

2023-03-13 22:06 UTC, tervay requested changes
just simplify some bridge speed stuff

2023-03-13 22:15 UTC, tervay requested changes

2023-03-13 22:15 UTC, tervay commented on src/main/java/frc/robot/commands/OnBridgeUntilMovement.java
> +    if((gridside == true && DriverStation.getAlliance() == Alliance.Blue) || (gridside == false && DriverStation.getAlliance() == Alliance.Red)){
You can simplify this:

```
(gridside && DriverStation.getAlliance() == Alliance.Blue) || (!gridside && DriverStation.getAlliance() == Alliance.Red)
```

you don't need to compare booleans to `true` or `false`.

2023-03-13 22:15 UTC, tervay commented on src/main/java/frc/robot/commands/OnBridgeUntilMovement.java
>      robotSpeed = 2 * (gridside ? 1 : -1) * (DriverStation.getAlliance() == Alliance.Red ? -1 : 1);
delete these now

2023-03-13 22:17 UTC, tervay approved these changes

2023-03-13 22:27 UTC, merged